package recursos;
// Generated 09-dic-2019 22:46:19 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Correo generated by hbm2java
 */
@Entity
@Table(name = "correo", catalog = "profesor")
public class Correo implements java.io.Serializable {

	private Integer id;
	private Profesor profesor;
	private String direccion;
	private String proveedor;

	public Correo() {
	}

	public Correo(Profesor profesor) {
		this.profesor = profesor;
	}

	public Correo(Profesor profesor, String direccion, String proveedor) {
		this.profesor = profesor;
		this.direccion = direccion;
		this.proveedor = proveedor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profesor_id", nullable = false)
	public Profesor getProfesor() {
		return this.profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	@Column(name = "direccion", length = 50)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "proveedor", length = 50)
	public String getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(String proveedor) {
		this.proveedor = proveedor;
	}

}
