package recursos;
// Generated 09-dic-2019 22:46:19 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modulo generated by hbm2java
 */
@Entity
@Table(name = "modulo", catalog = "profesor")
public class Modulo implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Float creditos;
	private Set<Profesor> profesors = new HashSet<Profesor>(0);

	public Modulo() {
	}

	public Modulo(String nombre, Float creditos, Set<Profesor> profesors) {
		this.nombre = nombre;
		this.creditos = creditos;
		this.profesors = profesors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "creditos", precision = 12, scale = 0)
	public Float getCreditos() {
		return this.creditos;
	}

	public void setCreditos(Float creditos) {
		this.creditos = creditos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modulo")
	public Set<Profesor> getProfesors() {
		return this.profesors;
	}

	public void setProfesors(Set<Profesor> profesors) {
		this.profesors = profesors;
	}

}
